### ISSUE TITLE
Test Bot by playing a game (workflow)

### ISSUE THREAD

**Issue by TheLibots** [AttackingOrDefending/lidraughts-bot#14]
Implement a workflow to test a bot by playing a game

**Comment by AttackingOrDefending** [comment]
I will implement this when it is merged in lichess-bot.

**Comment by TheLibots** [comment]
@AttackingOrDefending that Pr for lichess not for lidraughts if you can pls implement for this repo (draughts)

**Comment by AttackingOrDefending** [comment]
As I said in #11:

> I will implement the when they are merged because they may add more changes to the PRs before they are accepted.
