### ISSUE TITLE
Frisian And Frysk! Bot client error  

### ISSUE THREAD

**Issue by SriMethan** [AttackingOrDefending/lidraughts-bot#28]
Logs file playing Frisian and Frysk! Backing off play_game(...) for 1.6s (IndexError: list index out of range)

**Comment by SriMethan** [comment]
@AttackingOrDefending These variants can be playable with the old version of bot client

**Comment by AttackingOrDefending** [comment]
Should be fixed now. Can you update to the newest version and test?

**Comment by SriMethan** [comment]
Fixed Thanks!
