### ISSUE TITLE
Setup the strength

### ISSUE THREAD

**Issue by ttBOT-on-Lichess** [AttackingOrDefending/lidraughts-bot#94]
How can I setup the Scan's strength?

**Comment by AttackingOrDefending** [comment]
You can either compile the [modified version of Scan](https://github.com/RoepStoep/scan-3.1) used on lidraughts which adds difficulty levels, or add [go options](https://github.com/AttackingOrDefending/lidraughts-bot/blob/main/config.yml.default#L27) to reduce its strength.

**Comment by ttBOT-on-Lichess** [comment]
Thanks a lot!
